name: photo_upload
description: A module to handle photo upload
version: 0.4.6
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage_service:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/firebase_storage_service
    version: ^0.3.0
  layout_builder:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/layout_builder
    version: ^0.18.0
  firebase_storage: ^10.0.5
  flutter_riverpod: ^1.0.0
  freezed_annotation: ^0.15.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  freezed: ^0.15.0