name: firebase_auth_service
description: Wrapper package for FirebaseAuth
version: 0.3.3
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter_riverpod: ^1.0.0-dev.7
  freezed_annotation: ^0.14.3
  google_sign_in: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  freezed: ^0.14.5
  json_serializable: ^5.0.0

flutter: