name: sign_in
description: Sign-in Flow Management for Flutter & Firebase
publish_to: 'none'
version: 5.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    version: ^0.2.4
  firestore_service:
    git: 
      url: https://github.com/julienlebren/flutter_packages
      path: packages/firestore_service
    version: ^0.2.0
  firebase_storage_service:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/firebase_storage_service 
    version: ^0.3.0 
  layout_builder:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/layout_builder
    version: ^2.5.4
  localization:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    version: ^1.1.3
  modal_bottom_sheet:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/modal_bottom_sheet
    version: ^2.0.2-dev.2
  cloud_firestore: ^3.1.0
  cloud_functions: ^3.2.14
  firebase_auth: ^3.1.3
  firebase_storage: ^10.1.0
  freezed_annotation: ^1.1.0
  flutter_libphonenumber: 1.1.0
  flutter_login_facebook: ^1.1.0
  flutter_riverpod: ^1.0.0
  google_sign_in: ^5.1.1
  intl: ^0.17.0
  pinput: ^2.2.9
  the_apple_sign_in: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  
flutter:
  generate: true
  assets:
    - assets/images/