name: firestore_service
description: Wrapper for Cloud Firestore
version: 0.2.2
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^3.4.9
  flutter_riverpod: ^1.0.4

flutter: